name = "diffrentcontent"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "modules"
main = "./dist/index.js"
dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "diffrentcontent"
database_id = "your-database-id" 